#+TITLE: rails from scratch
#+AUTHOR: Hoyoul Park
#+DESCRIPTION: Org-HTML export made simple.
#+KEYWORDS:  org-mode, export, html, theme, style, css, js, bigblow
#+LANGUAGE:  en
#+OPTIONS:   H:4 toc:t num:2
#+MACRO: color @@html:<font color=></font>@@
#+PROPERTY:  header-args :padline no
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
#+LATEX_HEADER: \usepackage{kotex}
#+latex_header: \hypersetup{colorlinks=true}

* 0_맨처음 해야 하는것
#+begin_note
local에서 작업할수 있는 환경을  만든다. gorails에서 지시하는대로 한다. 그 다음 capistrano를 통해 운영서버에 적용하는 환경을 만들것이다. 두 환경은 하나의 rails project에서 동시에 운영된다. 아무 문제 없다. 즉 capistrano 설정을 하면 local에서 작업하지 못하고, local에서 별도로 rails new railsproject를 사용해서 local용을 만들 필요가 없다는 것이다. 하나의 rails 프로젝트에서 test하고 rails s로 local test하고 제대로 되면 운영서버로 배포하는 형태를 가지면 된다.
#+end_note
** local 개발환경
*** ruby 설치(with rbenv)
#+begin_note
rails는 ruby version을 탄다. rails와 ruby version이 궁합이 맞아야 하고, gem들도 맞아야 한다. ruby설치는 rbenv를 사용한다.
#+end_note
#+begin_note
rbenv는 여러버전의 ruby를 설치할 수 있는데, 이것이 가능한것은 ruby-build라는 plugin이 있기에 가능하다. rbenv install 3.14 이런식으로 ruby를 설치하는것은 rbenv-build에 있는 rbenv-install에 의해서 가능한 것이다.
#+end_note

 #+begin_tip
 brew install rbenv ruby-build

# Add rbenv to bash so that it loads every time you open a terminal
echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.zshrc
source ~/.zshrc

# Install Ruby
rbenv install 3.0.1
rbenv global 3.0.1
ruby -v
 #+end_tip
*** git 설치와 설정
#+begin_note
rails는 기본적으로 git init의 과정으로 local git을 설정한다. 그래서 git이 이미 system에 설치되어 있어야 하고, git에 대한 설정을 해야 한다. 그리고 github에 저장해야 하기 때문에, ssh도 만들어야 한다.
#+end_note
 #+begin_tip
git config --global color.ui true
git config --global user.name "holy"
git config --global user.email "holy@fastmail.com"
ssh-keygen만 해도 된다.
 #+end_tip
*** rails 설치
#+begin_note
gem은 ruby를 설치하면 자동으로 같이 설치된다. gem을 이용해서 rails를 설치한다.
gem install rails -v 6.1.3.2 
#+end_note
#+begin_note
한가지 특이한건, gem으로 설치한 rails를 사용하기 위해선 rbenv에게
rails가 설치되었다는 것을 알려줘야 한다는 것이다.
#+end_note
 #+begin_tip
 rbenv rehash를 해야만 rails를 사용할 수 있다.
 #+end_tip
*** Database 설치
#+begin_note
brew install mysql
brew services start mysql
#+end_note
